// Dactyl Manuform Hotswap
#pragma once

// Basic Config

#define SPLIT_POINTING_ENABLE
//#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define PMW33XX_CS_PIN GP21
//#define POINTING_DEVICE_CS_PIN GP21

#define SPLIT_TRANSACTION_IDS_KB RPC_ID_KB_CONFIG_SYNC
//#define CHARYBDIS_MAX_DEFAULT_DPI_MULTIPLIER 0x08
//#define CHARYBDIS_BASE_DEFAULT_DPI_MULTIPLIER 0x02

#ifndef CHARYBDIS_MINIMUM_DEFAULT_DPI
#  define CHARYBDIS_MINIMUM_DEFAULT_DPI 200
#endif // CHARYBDIS_MINIMUM_DEFAULT_DPI

#ifndef CHARYBDIS_DEFAULT_DPI_CONFIG_STEP
#  define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200
#endif // CHARYBDIS_DEFAULT_DPI_CONFIG_STEP

#ifndef CHARYBDIS_MINIMUM_SNIPING_DPI
#  define CHARYBDIS_MINIMUM_SNIPING_DPI 100
#endif // CHARYBDIS_MINIMUM_SNIPING_DPI

#ifndef CHARYBDIS_SNIPING_DPI_CONFIG_STEP
#  define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100
#endif // CHARYBDIS_SNIPING_DPI_CONFIG_STEP
#ifndef CHARYBDIS_DRAGSCROLL_DPI
#  define CHARYBDIS_DRAGSCROLL_DPI 200
#endif // CHARYBDIS_DRAGSCROLL_DPI
#ifndef CHARYBDIS_POINTER_ACCELERATION_ENABLE
#  define CHARYBDIS_POINTER_ACCELERATION_ENABLE
#endif // CHARYBDIS_POINTER_ACCELERATION_ENABLE

// End of Basic Config
