AVR_USE_MINIMAL_PRINTF = yes
COMBO_ENABLE           = yes
COMMAND_ENABLE         = no
CONSOLE_ENABLE         = no
EXTRAKEY_ENABLE        = yes
KEY_OVERRIDE_ENABLE    = no
LEADER_ENABLE          = yes
LTO_ENABLE             = yes
MAGIC_ENABLE           = no
MIDI_ENABLE            = no
MOUSEKEY_ENABLE        = yes # Mouse keys
NKRO_ENABLE            = no  # Enable N-Key Rollover
OLED_ENABLE            = no
QMK_SETTINGS           = no
RAW_ENABLE             = no
RGBLIGHT_ENABLE        = yes # Enable WS2812 RGB underlight.
SPACE_CADET_ENABLE     = no
SWAP_HANDS_ENABLE      = no      # Enable one-hand typing
TAP_DANCE_ENABLE       = yes
VIAL_ENABLE            = yes # Enable VIAL
VIAL_INSECURE          = yes # Disable security
VIA_ENABLE             = yes # Enable VIA
VIRTSER_ENABLE         = no
