COMBO_ENABLE        = yes
CONSOLE_ENABLE      = no
EXTRAKEY_ENABLE     = yes
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE          = yes
MOUSEKEY_ENABLE     = yes      # Mouse keys
OLED_DRIVER         = SSD1306
OLED_ENABLE         = no
QMK_SETTINGS        = no
RGBLIGHT_ENABLE     = yes      # Enable WS2812 RGB underlight.
TAP_DANCE_ENABLE    = yes
VIAL_ENABLE         = yes      # Enable VIAL
VIAL_INSECURE       = yes      # Disable security
VIA_ENABLE          = yes      # Enable VIA
